allowBuilds:
  msgpackr-extract: false
enableGlobalVirtualStore: true
patchedDependencies:
  '@executor-js/config@1.6.8': patches/@executor-js__config@1.6.8.patch
  '@executor-js/plugin-mcp@1.6.8': patches/@executor-js__plugin-mcp@1.6.8.patch
  '@executor-js/sdk@1.6.8': patches/@executor-js__sdk@1.6.8.patch
peerDependencyRules:
  allowedVersions:
    effect: 4.0.0-rc.115
